#!/usr/bin/python3
def raise_exception():
    result = 1 + []
    return result
